import DisplayImage from "@/Components/DisplayImage"
import styles from "@/styles/Home.module.css"
import ColorThief from "colorthief"
import Head from "next/head"
import { useState } from "react"

const gallery = <i className="fas fa-images"></i>

export default function Home() {
  const [uploadedImage, setUploadedImage] = useState(null)
  const [colorPalette, setColorPalette] = useState(null)

  const uploadImage = e => {
    const file = e.target.files[0]
    const reader = new FileReader()

    reader.onload = async event => {
      const img = new Image()

      img.onload = () => {
        const colorThief = new ColorThief()
        const colorPalette = colorThief.getPalette(img, 6)
        setUploadedImage(event.target.result)
        setColorPalette(colorPalette)
      }
      img.src = event.target.result
    }

    reader.readAsDataURL(file)
  }

  if (typeof window !== "undefined") {
    const blob = document.getElementById("blob")

    document.body.onpointermove = event => {
      const { clientX, clientY } = event

      blob.animate(
        {
          left: `${clientX}px`,
          top: `${clientY}px`,
        },
        { duration: 3000, fill: "forwards" }
      )
    }
  }

  return (
    <>
      <Head>
        <title>Colour Palette</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <div id="blob"></div>
      <div id="blur"></div>
      <h1 className="header">Colour Palette Generator</h1>
      <div>
        <div className="input">
          <label htmlFor="file"> {gallery} Upload Image </label>
          <input type="file" id="file" hidden onChange={uploadImage} />
        </div>
      </div>
      <main className={styles.main}>
        <DisplayImage
          uploadedImage={uploadedImage}
          colorPalette={colorPalette}
          gallery={gallery}
        />
      </main>
    </>
  )
}
